name: Генерация страницы загрузки

on:
  push:
    branches:
      - main

jobs:
  generate-download-page:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Список файлов в docs/d и генерация ${index}
        run: |
          index=./docs/index.html
          echo "<!DOCTYPE html>" > ${index}
          echo "<html lang='ru'>" >> ${index}
          echo "<head>" >> ${index}
          echo "  <meta charset='UTF-8'>" >> ${index}
          echo "  <title>Страница загрузки</title>" >> ${index}
          echo "</head>" >> ${index}
          echo "<body>" >> ${index}
          echo "  <h1>Загрузить файлы | Downloads</h1>" >> ${index}
          echo "<hr>" >> ${index}

          # Loop through files in docs/d/ and create download links with file size
          for file in src/download/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              filesize=$(stat --format=%s "$file")
              # Convert size to human-readable format
              human_size=$(numfmt --to=iec --suffix=B "$filesize")

              mv "${file}" "./docs/d/$(basename ${file})"
              echo "  <p><a href='download/$(basename ${filename})' download>$filename</a> - $human_size</p>" >> ${index}
            fi
          done

          echo "<hr>" >> ${index}

          # Inject external JavaScript from docs/s/s.js
          echo "<script>" >> ${index}
          cat src/script/s.js >> ${index}
          echo "</script>" >> ${index}

          echo "</body>" >> ${index}
          echo "</html>" >> ${index}

          # Inject style sheet
          echo "<style>" >> ${index}
          cat src/style/style.css >> ${index}
          echo "</style>" >> ${index}

      - name: Коммит и отправка изменений
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Обновить страницу загрузки'
          push: true
