name: Генерация страницы загрузки

on:
  push:
    branches:
      - main

jobs:
  generate-download-page:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Список файлов в docs/d и генерация index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='ru'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <title>Страница загрузки</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>Загрузить файлы | Downloads</h1>" >> index.html
          echo "<hr>" >> index.html

          # Loop through files in docs/d/ and create download links with file size
          for file in docs/d/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              filesize=$(stat --format=%s "$file")
              # Convert size to human-readable format
              human_size=$(numfmt --to=iec --suffix=B "$filesize")
              echo "  <p><a href='docs/d/$filename' download>$filename</a> - $human_size</p>" >> index.html
            fi
          done

          echo "<hr>" >> index.html

          # Inject external JavaScript from docs/s/s.js
          echo "<script>" >> index.html
          cat docs/s/s.js >> index.html
          echo "</script>" >> index.html

          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Коммит и отправка изменений
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Обновить страницу загрузки'
          push: true
