name: Генерация страницы загрузки

on:
  push:
    branches:
      - main

jobs:
  generate-download-page:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v2

      - name: Список файлов в docs/d и генерация index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='ru'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <title>Страница загрузки</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>Загрузить файлы</h1>" >> index.html
          echo "  <ul>" >> index.html

          for file in docs/d/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "    <li><a href='docs/d/$filename' download>$filename</a></li>" >> index.html
            fi
          done

          echo "  </ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Коммит и отправка изменений
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: '.'
          push: true
